### ISSUE TITLE
Package 'mysql-client' has no installation candidate

### ISSUE THREAD

**Issue by christianhg** [henrikbak/docker-drop#1]
Hey!

I'm trying out this project for an existing Drupal site, but upon running `docker-compose up -d` I get the following error:

```
Package mysql-client is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'mysql-client' has no installation candidate
ERROR: Service 'php' failed to build: The command '/bin/sh -c apt-get update && apt-get install -y     libfreetype6-dev     libjpeg62-turbo-dev     libpng-dev     mysql-client     wget     curl     git     zip     unzip' returned a non-zero code: 100
```

Are some Docker image versions out of sync?

**Comment by henrikbak** [comment]
Hi Christian! :)

It seems like til mysql-client package is no longer available in php-fpm. I replaced it with mariadb-client and that should do the trick.

**Comment by christianhg** [comment]
Hi Henrik and thanks!

I actually managed to get my site up and running by removing the `php-fpm` `Dockerfile`. I didn't need all the bells and whistles :)
